### ISSUE TITLE
No DGW3 fork

### ISSUE THREAD

**Issue by Sandokaaan** [ibithub/ibithub#2]
src/main.cpp
lines 1395-1396: 
`        if (pindexLast->nHeight+1 >= 100000) { DiffMode = 2; }`
`        else if (pindexLast->nHeight+1 >= 147000) { DiffMode = 3; } // DGW3`

The `else` command effectivelly prevented the switch to DGW3, because it is evaluated only if nHeight IS NOT > 100000.
If you intended to do the fork, delete `else` and change 147000 appropriatally. Otherwise, consider this issue as irrelevant.

**Comment by ibithub** [comment]
Thank you for your input. Issue resolved with
commit 6fbc8830c9679e8798d0c9044c28214c34329421
